### ISSUE TITLE
Does relativeURLs=true in hugo config affect deployment

### ISSUE THREAD

**Issue by rossbar** [scientific-python/scientific-python.org#13]
Added in #12 to get the website preview working in CI. Not sure what the impact is on the deployed website, so revisit this if there are deployment issues.

**Comment by jarrodmillman** [comment]
@stefanv It looks like the CircleCI webserver doesn't automatically server index.html when you request a directory.  For example,
instead of 
https://6-142606827-gh.circle-artifacts.com/0/public/about/
we had to do
https://6-142606827-gh.circle-artifacts.com/0/public/about.html
I did that in cc389955a6bafb9013bc03e8cd5a66007d1ab210.  Also instead of
https://6-142606827-gh.circle-artifacts.com/0/public/specs/spec-0000/
we had to do
https://6-142606827-gh.circle-artifacts.com/0/public/specs/spec-0000.html
I did that in 71d434b00682da51fbcfc52f229de6c1dc173135.  I fixed a couple more issues in 0e3e87c2372f01ad5d5f2e0a1a9795e52b208a59.

**Comment by stefanv** [comment]
I don't think that's correct, because https://6-142606827-gh.circle-artifacts.com/0/public/about/index.html also does not render.

**Comment by jarrodmillman** [comment]
I probably shouldn't have used the links.  I updated it to remove them, but this doesn't work
https://6-142606827-gh.circle-artifacts.com/0/public/about/index.html
because that is the artifact where we used
https://6-142606827-gh.circle-artifacts.com/0/public/about.html

I don't have links to the artifact from when we were doing something where
https://<>-gh.circle-artifacts.com/0/public/about/
didn't work, but
https://<>-gh.circle-artifacts.com/0/public/about/index.html
did.  I just hand copied the one that worked and edited it by hand.

**Comment by jarrodmillman** [comment]
We use nice urls by default (and change ``config.toml`` in ``.circleci/config.yml`` as needed) see ca005553b66f1dfd2cf08c643b6c4d74a4592f57.

**Comment by stefanv** [comment]
I think that commit takes the wrong approach. URLs should not be custom munged, and specs should be listed at /specs.

**Comment by jarrodmillman** [comment]
They are when we deploy them.  But there is no way to do what you want with circle ci.

**Comment by stefanv** [comment]
Sorry, I didn't realize this was CircleCI specific---seems like a fine hack for that.  @rossbar Any progress on Netlify previews?

**Comment by rossbar** [comment]
> Any progress on Netlify previews?

Not yet, will put it on the list for today!

**Comment by jarrodmillman** [comment]
@stefanv I meant to ask you about this yesterday, so it is good that you responded.  We may also want to move the ``relativeURLs=true`` to the circleci specific stuff for now as well.

**Comment by rossbar** [comment]
> We may also want to move the relativeURLs=true to the circleci specific stuff for now as well.

+1 - if the `relativeURLs` config option affects the deployed site, it would be simple enough to just add `echo "relativeURLs=true" >> config.toml` to the circleCI workflow. 

I'm looking at netlify now, so maybe this will all be moot.

**Comment by jarrodmillman** [comment]
I moved ``relativeURLs=true`` to the circleci config #39.

**Comment by stefanv** [comment]
It should be inconsequential for the real site, whether it generates absolute or relative URLs as long as we use the relative link shortcode.  It's odd that Hugo doesn't always see links as relative.

**Comment by stefanv** [comment]
The site previews are now on Netlify at https://scientific-python-org.netlify.app
