### ISSUE TITLE
Bikeshed: emoji doesn't render

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/scientific-python.org#75]
Local problem that I should probably fix, but it may affect more future viewers of the page:
The draft document emoji doesn't render for me either on the desktop or on the phone, consider using a more basic one.
E.g. here: https://draft.scientific-python.org/specs/spec-0000/

**Comment by stefanv** [comment]
Thanks, @bsipocz, I've noticed this on my phone too.  Perhaps we should resort to a small image instead.

**Comment by jarrodmillman** [comment]
Would a banner that stays visible as the page is scrolled down be possible?   Since the draft status is a central part of the SPEC lifecycle, it would be nice to make it more prominent.

I don't think we need an emoji or an image.  We don't really need much text.  Maybe just the word "Draft" like a watermark would work.

**Comment by bsipocz** [comment]
The emoji was dropped a while ago, so I'm closing this now.

**Comment by jarrodmillman** [comment]
It is a theme isssue and shows up on multiple websites. Here is another example:
![2023-08-14T11:33:45,280752135-07:00](https://github.com/scientific-python/scientific-python.org/assets/123428/58107e6c-4369-4e7a-902a-5722ebe22759)

**Comment by stefanv** [comment]
Those may still be referring to font-awesome Unicode. I'll take a look when I'm back at work.

**Comment by jarrodmillman** [comment]
Adam can take care of this as well.

**Comment by bsipocz** [comment]
This seems to be resolved at some point.
